spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dream?characterEncoding=utf8&useSSL=true&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    username: root
    password: root
    maxActive: 20
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.java.activiti.model


server:
  port: 8183


logging:
  level:
    com.oa.system.dao: debug


